#!/bin/bash
docker container kill $(docker ps | grep "nginx-server" | awk '{ print $1 }')
docker rm $(docker ps -a | grep "nginx-server" | awk '{ print $1 }')
docker build -t nginx-server .
docker run -it -d --name nginx-server --restart=always --network=host -p 80:80 -v /mnt/data/Programs/web-server:/www nginx-server
